### ISSUE TITLE
Undocked map doesn't show npc positionsv

### ISSUE THREAD

**Issue by robbely** [efa/Wilderland#2]
Undocked map doesn't show npc positions

Using WL2.10b_2023-12-03_WinMxe_x86_64_64bit

**Comment by efa** [comment]
yes, it is in my to do list. Thank you to open an issue to remind me that

**Comment by efa** [comment]
can you please send me some feedback on Wilderland in [Discussion](https://github.com/efa/Wilderland/discussions) area?

**Comment by efa** [comment]
should be solved with current release: https://github.com/efa/Wilderland/releases/tag/v2.10

**Comment by robbely** [comment]
Works great now - thanks for the fix :)
Apologies re not leaving a review - I'm not very good in that area, but it's a great way to play with an old fave :)
